version: '3.1'

services:
  lens-plumemo-server:
    image: lensson/lens-plumemo-server:latest
    container_name: lens-plumemo-server
    restart: unless-stopped
    ports:
      - 9201:9000
    networks:
      solution_backnet:
        ipv4_address:  172.28.0.201
    environment:
      MYSQL_USERNAME: lens
      MYSQL_PASSWORD: lens
    volumes:
      - ~/containers/lens-plumemo-server/files:/files
      - ~/containers/lens-plumemo-server/logs:/logs
  lens-plumemo-admin-client:
    image: lensson/lens-plumemo-admin-client:latest
    container_name: lens-plumemo-admin-client
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - 8202:80
    networks:
      solution_backnet:
        ipv4_address:  172.28.0.202
    restart: unless-stopped
  lens-plumemo-flutter-client:
    container_name: lens-plumemo-flutter-client
    image: lensson/lens-plumemo-flutter-client:latest
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - 8203:80
    networks:
      solution_backnet:
        ipv4_address:  172.28.0.203
    restart: unless-stopped
networks:
  solution_backnet:
    external: true
