version: '3.1'

services:
  lens-plumemo-admin-client:
    image: lensson/lens-plumemo-admin-client:latest
    container_name: lens-plumemo-admin-client
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - 8202:80
    networks:
      solution_backnet:
        ipv4_address:  172.28.0.202
    restart: unless-stopped
networks:
  solution_backnet:
    external: true 
