version: '3.1'
services:
  lens-sentinel:
    image: lensson/sentinel-dashboard:1.8.1
    container_name: sentinel-dashboard
    ports:
      - 8718:8080
      - 8719:8719
    networks:
      solution_backnet:
        ipv4_address:  172.28.0.24
    restart: unless-stopped
    environment:
      JAVA_OPTS: "-Dserver.port=8080 -Dcsp.sentinel.dashboard.server=localhost:8080 -Dproject.name=sentinel-dashboard -Djava.security.egd=file:/dev/./urandom -Dcsp.sentinel.api.port=8719"
networks:
  solution_backnet:
    external: true
