version: '3.1'

services:
  lens-blog-admin-backend:
    container_name: lens-blog-admin-backend
    image: lensson/lens-blog-admin-backend:latest
    restart: unless-stopped
    env_file:
      - ./env/lens-mac.properties
    environment:
      lens-nacos: 192.168.50.72
    ports:
      - 9002:9002
    networks:
      - solution_backnet
networks:
  solution_backnet:
    external: true 
