version: '3.1'

services:
  lens-blog-monitor:
    container_name: lens-blog-monitor
    image: lensson/lens-blog-monitor:latest
    restart: unless-stopped
    env_file:
      - ./env/lens-mac.properties
    ports:
      - 9020:9020
    networks:
      - solution_backnet
  lens-blog-sms:
    container_name: lens-blog-sms
    image: lensson/lens-blog-sms:latest
    restart: unless-stopped
    env_file:
      - ./env/lens-mac.properties
    ports:
      - 9011:9011
    networks:
      - solution_backnet
networks:
  solution_backnet:
    external: true 
