version: "3.1"
services:
  lens-nacos:
    image: nacos/nacos-server:1.3.1
    container_name: lens-nacos
    env_file:
      - ./lens-nacos/lens-nacos.env
    volumes:
      - ./lens-nacos/nacos-logback.xml:/home/nacos/conf/nacos-logback.xml
      - ./lens-nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
      - ~/containers/lens-nacos/logs/:/home/nacos/logs
    ports:
      - "8848:8848"
      - "9555:9555"
    networks:
      - solution_backnet
    restart: unless-stopped
networks:
  solution_backnet:
    external: true
