version: '3.1'

services:
  lens-plumemo-flutter-web:
    container_name: lens-plumemo-flutter-web
    image: lensson/flutter_blog
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - 8301:80
    networks:
      - malakj_malanet
    restart: unless-stopped
networks:
  malakj_malanet:
    external: true 
