version: '3.5'

services:
  lens-blog-vue-learning:
    container_name: lens-blog-vue-learning
    image: lensson/lens-blog-vue-learning:latest
    command: [nginx-debug, '-g', 'daemon off;']
    restart: unless-stopped
    env_file:
      - env/solution.env
    ports:
      - 8003:80
    networks:
      solution_backnet:
        ipv4_address:  172.28.0.183
networks:
  solution_backnet:
    external: true