version: '3.1'

services:
  lens-plumemo:
    image: lensson/plumemo:latest
    container_name: lens-plumemo
    restart: unless-stopped
    ports:
      - 9201:9000
    networks:
      solution_backnet:
        ipv4_address:  172.28.0.201
    environment:
      MYSQL_USERNAME: lens
      MYSQL_PASSWORD: lens
    volumes:
      - ~/containers/lens-plumemo/files:/files
      - ~/containers/lens-plumemo/logs:/logs

networks:
  solution_backnet:
    external: true 
