version: '3.5'

services:
  lens-blog-spider:
    container_name: lens-blog-spider
    image: lensson/lens-blog-spider:latest
    restart: unless-stopped
    env_file:
      - env/solution.env
    volumes:
      - ~/containers/logs/lens-blog-spider:/root/containers/logs/lens-blog-spider
    ports:
      - 9014:9014
    networks:
      solution_backnet:
        ipv4_address:  172.28.0.114
networks:
  solution_backnet:
    external: true 