version: '3.1'

services:
  lens-plumemo-flutter-client:
    container_name: lens-plumemo-flutter-client
    image: lensson/lens-plumemo-flutter-client:latest
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - 8203:80
    networks:
      solution_backnet:
        ipv4_address:  172.28.0.203
    restart: unless-stopped
networks:
  solution_backnet:
    external: true 
