version: '3.1'

services:
  lens-gateway:
    container_name: lens-gateway
    image: lensson/lens-gateway:latest
    restart: always
    ports:
      - 8849:8849
    networks:
      - solution_backnet
    volumes:
      - ~/containers/lens-gateway/nacos/naming/public:/root/nacos/naming/public
    environment:
      nacos: lens-nacos
  lens-auth:
    container_name: lens-auth
    image: lensson/lens-auth:latest
    restart: always
    ports:
      - 8850:8850
    networks:
      - solution_backnet
    environment:
      nacos: lens-nacos
      redis: lens-redis
      lens-auth: lens-auth
networks:
  solution_backnet:
    external: true 
