version: '3.5'

services:
  lens-blog-admin-backend:
    container_name: lens-blog-admin-backend
    image: lensson/lens-blog-admin-backend:latest
    restart: unless-stopped
    env_file:
      - env/lens-mac.env
    volumes:
      - ~/containers/logs/lens-blog-admin-backend:/root/containers/logs/lens-blog-admin-backend
    ports:
      - 9002:9002
    networks:
      - solution_backnet
networks:
  solution_backnet:
    external: true