version: "3.1"
services:
  lens-solr:
    image: solr:7.1.0
    container_name: lens-solr
    ports:
      - 8983:8983
    networks:
      solution_backnet:
        ipv4_address:  172.28.0.25/24
    restart: unless-stopped
networks:
  solution_backnet:
    external: true
