# Use root/example as user/password credentials
version: '3.5'
services:
  lens-mariadb:
    image: mariadb
    container_name: lens-mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - ~/containers/lens-mariadb/data:/var/lib/mysql
    ports:
      - 33306:3306
    networks:
      solution_backnet:
        ipv4_address: 172.28.0.11
  lens-mariadb-adminer:
    image: adminer
    container_name: lens-mariadb-adminer
    restart: unless-stopped
    depends_on:
      - lens-mariadb
    ports:
      - 38080:8080
    networks:
      solution_backnet:
        ipv4_address:  172.28.0.12
  lens-redis:
    image: redis
    container_name: lens-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - ~/containers/lens-redis/data:/data
      - ~/containers/lens-redis/conf/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      solution_backnet:
        ipv4_address:  172.28.0.13
networks:
  solution_backnet:
    driver: bridge
    name: solution_backnet
    ipam:
      config:
        - subnet: 172.28.0.0/24