version: '3.1'

services:
  lens-plumemo-admin-web:
    image: lensson/plumemo-admin
    container_name: lens-plumemo-admin-web
    command: [nginx-debug, '-g', 'daemon off;']
    ports:
      - 8100:80
    networks:
      solution_backnet:
        ipv4_address:  172.28.0.202
    restart: unless-stopped
networks:
  solution_backnet:
    external: true 
