version: '3.5'

services:
  lens-blog-spider:
    container_name: lens-blog-spider
    image: lensson/lens-blog-spider:latest
    restart: unless-stopped
    env_file:
      - env/lens-linux76.env
    volumes:
      - ~/containers/logs/lens-blog-spider:/root/containers/logs/lens-blog-spider
    ports:
      - 9014:9014
    networks:
      - solution_backnet
networks:
  solution_backnet:
    external: true 