version: '3.5'

services:
  lens-blog-backend:
    container_name: lens-blog-backend
    image: lensson/lens-blog-backend:latest
    restart: unless-stopped
    env_file:
      - env/lens-linux76.env
    volumes:
      - ~/containers/logs/lens-blog-backend:/root/containers/logs/lens-blog-backend
    ports:
      - 9001:9001
    networks:
      - solution_backnet
networks:
  solution_backnet:
    external: true 