version: '3.1'

services:
  gateway:
    container_name: gateway
    image: lensson/gateway:latest
    restart: always
    ports:
      - 8849:8849
    networks:
      - malakj_malanet
  ghzserver:
    container_name: gzhserver
    image: lensson/gzhserver:latest
    restart: always
    ports:
      - 9002:9002
    networks:
      - malakj_malanet


networks:
  malakj_malanet:
    external: true 
