version: '3.1'

services:
  gate:
    image: lensson/plumemo
    command: [nginx-debug, '-g', 'daemon off;']
    volumes:
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
      #- ./nginx/logs:/var/log/nginx
    ports:
      - 80:80
    networks:
      - malanet

networks:
  malanet:
    driver: bridge  