version: '3.1'

services:
  theme-default:
    image: lensson/theme-default
    command: [nginx-debug, '-g', 'daemon off;']
    #volumes:
      #- ./nginx/conf/conf.d:/etc/nginx/conf.d
      #- ./nginx/logs:/var/log/nginx
    ports:
      - 8001:80
    networks:
      - malalkj_malanet

networks:
  malalkj_malanet:
    external: true 