version: '3.1'

services:
  flutter-blog-demo:
    image: lensson/flutter_blog
    command: [nginx-debug, '-g', 'daemon off;']
    #volumes:
      #- ./nginx/conf/conf.d:/etc/nginx/conf.d
      #- ./nginx/logs:/var/log/nginx
    ports:
      - 8200:80
    networks:
      - malakj_malanet

networks:
  malakj_malanet:
    external: true 
