version: '3.1'

services:
  plumemo:
    image: lensson/plumemo:latest
    restart: always
    ports:
      - 9000:9000
    networks:
      - malakj_malanet

networks:
  malakj_malanet:
    external: true 
