# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - ~/containers/data/mysql:/var/lib/mysql
    ports:
      - 33306:3306
    networks:
      - malanet

  adminer:
    image: adminer
    container_name: db_adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 38080:8080
    networks:
      - malanet

  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ~/containers/data/redis:/data
      - ~/containers/conf/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - malanet

networks:
  malanet:
    driver: bridge