version: '3.1'

services:
  plumemo-admin:
    image: lensson/plumemo-admin:latest
    command: [nginx-debug, '-g', 'daemon off;']
    #volumes:
      #- ./nginx/conf/conf.d:/etc/nginx/conf.d
      #- ./nginx/logs:/var/log/nginx
    ports:
      - 8100:80
    networks:
      - malanet

networks:
  malanet:
    driver: bridge  
