version: "2"
services:
  nacos:
    image: nacos/nacos-server:1.3.1
    container_name: nacos
    env_file:
      - nacos/nacos-standlone-mysql.env
    volumes:
      - ~/logs/nacos/standalone-logs/:/home/nacos/logs
      - ./nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
    depends_on:
      - nacos-mysql
    ports:
      - "8848:8848"
      - "9555:9555"
    environment:
      nacos: nacos
      lens-auth: lens-auth
      redis: redis
    networks:
      - malakj_malanet
    restart: always

  nacos-mysql:
    container_name: nacos-mysql
    image: nacos/nacos-mysql:8.0.16
    env_file:
      - ./nacos/mysql.env
    volumes:
      - ~/data/nacos/mysql:/var/lib/mysql
    ports:
      - "43306:3306"
    networks:
      - malakj_malanet
networks:
  malakj_malanet:
    external: true
