version: '3.5'

services:
  lens-blog-admin-vue-frontend:
    container_name: lens-blog-admin-vue-frontend
    image: lensson/lens-blog-admin-vue-frontend:latest
    command: [nginx-debug, '-g', 'daemon off;']
    restart: unless-stopped
    env_file:
      - env/lens-ucloud.env
    ports:
      - 8002:80
    networks:
      - solution_backnet
networks:
  solution_backnet:
    external: true